# bx_enh_dbg_ini
SeeReg[0] = TRUE        # Exibir o conteúdo do registrador EAX
SeeReg[1] = TRUE        # Exibir o conteúdo do registrador EBX
SeeReg[2] = TRUE        # Exibir o conteúdo do registrador ECX
SeeReg[3] = TRUE        # Exibir o conteúdo do registrador EDX
SeeReg[4] = FALSE       # Exibir o conteúdo do registrador ESI
SeeReg[5] = FALSE       # Exibir o conteúdo do registrador EDI
SeeReg[6] = FALSE       # Exibir o conteúdo do registrador EBP
SeeReg[7] = FALSE       # Exibir o conteúdo do registrador ESP
SingleCPU = FALSE       # Exibir apenas o conteúdo do CPU 0 (em sistemas multiprocessados)
ShowIOWindows = TRUE    # Exibir janelas de I/O
ShowButtons = TRUE      # Exibir botões na interface
SeeRegColors = TRUE     # Exibir cores nos registradores
ignoreNxtT = TRUE       # Ignorar a próxima instrução (útil para depuração passo a passo)
ignSSDisasm = TRUE      # Ignorar a desassemblagem da pilha (Stack Segment)
UprCase = 0             # Exibir texto em maiúsculas (0 = desativado, 1 = ativado)
DumpInAsciiMode = 3     # Modo de exibição de dump (0 = hexadecimal, 1 = ASCII, 2 = ambos, 3 = automático)
isLittleEndian = TRUE   # Exibir dados em formato little-endian
DefaultAsmLines = 512   # Número padrão de linhas a exibir na janela de desassemblagem
DumpWSIndex = 0         # Índice da janela de dump a ser usada
DockOrder = 0x123       # Ordem de encaixe das janelas (1 = CPU, 2 = I/O, 3 = Registradores)
ListWidthPix[0] = 167   # Largura da janela de desassemblagem em pixels
ListWidthPix[1] = 144   # Largura da janela de dump em pixels
ListWidthPix[2] = 423   # Largura da janela de registradores em pixels
MainWindow = 0, 0, 738, 500 # Posição e tamanho da janela principal (x, y, largura, altura)
FontName = Normal       # Nome da fonte utilizada na interface
